config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :philosophers do
    resources :dinners, only: [:index, :show, :new, :create]
  end
  get "/profile", to: "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :user
  belongs_to :philosopher

  validates :date, presence: true
  validates :length, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
  belongs_to :user
  validates :age, numericality: { greater_than: 0 }
  validates :location, :bio, :price_per_hour, :preferred_topic, :philosophical_focus, :dress_code, :nationality, :communication_style, presence: true
  has_many :dinners
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  before_save :sanitize_address

  private

  def sanitize_address
    self.location = location.strip
    # self.address = address.gsub(/[^0-9A-Za-z]/, '')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :philosophers
  has_many :dinners

  has_one_attached :photo

  # validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :password, :email, :password_confirmation, :photo, :philosopher)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :password, :email, :password_confirmation, :photo, :philosopher)}
  end
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  before_action :authenticate_user!

  def new
    @philosopher = Philosopher.find(params[:philosopher_id])
    @dinner = @philosopher.dinners.build
  end

  def create

    @philosopher = Philosopher.find(params[:philosopher_id])
    @dinner = Dinner.new(dinner_params)
    @dinner.philosopher = @philosopher
    @dinner.user = current_user
    if @dinner.save
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @dinner = Dinner.find(params[:id])
  end

  private

  def dinner_params
    params.require(:dinner).permit(:date, :length, :credit_card_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @user = current_user
  end
end

app/controllers/philosophers_controller.rb
class PhilosophersController < ApplicationController
    before_action :set_philosopher, only: [:show, :edit, :update]
    before_action :authenticate_user!, only: [:new, :create]

    # GET /philosophers
    def index
      if params[:query].present?
        @philosophers = Philosopher.joins(:user).where("users.username ILIKE ?", "%#{params[:query]}%")
      else
        @philosophers = Philosopher.all
      end
      @markers = @philosophers.geocoded.map do |philosopher|
        {
          lat: philosopher.latitude,
          lng: philosopher.longitude,
          url: philosopher_path(philosopher),
          info_window_html: render_to_string(partial: "info_window", locals: {philosopher: philosopher})
        }
      end
    end

    # GET /philosophers/:id
    def show
      @philosopher = Philosopher.find(params[:id])
        @marker = [{
          lat: @philosopher.latitude,
          lng: @philosopher.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {philosopher: @philosopher})
        }]
      @dinner = Dinner.new
    end

    # GET /philosophers/new
    def new
      if current_user.philosopher
        redirect_to some_other_path, alert: "You are already registered as a philosopher."
      else
        @philosopher = Philosopher.new
      end
    end

    # POST /philosophers
    def create
      @philosopher = current_user.philosophers.build(philosopher_params)

      if @philosopher.save!
        redirect_to @philosopher, notice: 'Philosopher was successfully created.'
        current_user.update(philosopher: true)
      else
        render :new
      end
    end

    # GET /philosophers/:id/edit
    def edit
      # The view will display the edit form for the philosopher
    end

    # PATCH/PUT /philosophers/:id
    def update
      if @philosopher.update(philosopher_params)
        redirect_to @philosopher, notice: 'Philosopher was successfully updated.'
      else
        render :edit
      end
    end

    private

    def set_philosopher
      @philosopher = Philosopher.find(params[:id])
    end

    def philosopher_params
      params.require(:philosopher).permit(:age, :location, :availability, :bio, :price_per_hour, :preferred_topic, :philosophical_focus, :dress_code, :nationality, :communication_style, :user_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dinners/index.html.erb
<h4>My dinners</h4>
<% @dinners.each do |dinner| %>
  <div class="co-12 col-sm-6 col-md-4 mb-3">
    <%= link_to dinner_path(dinner), class:"text-decoration-none" do %>
      <div class="card-category" data-aos="zoom-in">
        <p>Your dinner between you and<%= dinner.philosopher.name%> will happen on this date:<%= dinner.date %></p>
        <p>The status of this dinner is:<%= dinner.status %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <title>PhilosoFeast</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing-page">
<div class="mytext">
<h5>Tired of boring conversation topics?</h5>
<h2>Have dinner with a philosopher!</h2>
<%= link_to 'Explore the philosophers', philosophers_path, class: 'mybutton' %>
</div>
</div>

app/views/pages/profile.html.erb
<div class="profile m-4">
<% if @user.dinners.any? %>
  <h4>Your Dinners:</h4><br>
  <% @user.dinners.each do |dinner| %>
    <div class="dinner mb-4 d-flex justify-content-around rounded-4">
    <div class="m-3 rounded-circle myavatar align-self-center" style="background-image: url('<%= cl_image_path(@current_user.photo.key) %>')"></div>
      <div class="dinner-info align-self-center text-center">
      <p class="fs-5"><strong><em>You have a dinner with <%= dinner.philosopher.user.username %>!</em></strong></p>
      <p class="fs-5">📅 <%= dinner.date.to_date %></p>
      <p class="fs-5">🕰️ <%= dinner.length %>h</p>
      <p class="fs-5">📍<%= dinner.philosopher.location %></p>
      </div>
    <div class="m-3 rounded-4 hisavatar" style="background-image: url('<%= cl_image_path(dinner.philosopher.user.photo.key) %>')"></div>
    </div>
  <% end %>
      <div class="d-flex justify-content-end"><%= link_to 'Book another dinner!', philosophers_path, class: 'mybutton' %></div>
<% else %>
<div class="d-flex justify-content-center">

<div class="flex-column">
<div class="nodinner text-center text-light">
  <br><p class="fs-5">You don't have any dinner booked 😔</p>
</div>
<br>
<div class="d-flex justify-content-center">
  <%= link_to 'Book a dinner with a philosopher!', philosophers_path, class: 'mybutton' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/philosophers/_info_window.html.erb
<h4><%= link_to philosopher.user.username, philosopher_path(philosopher) %></h4>
<%= cl_image_tag philosopher.user.photo.key, class: "w-50 img", alt: "Philosopher image" %>

app/views/philosophers/index.html.erb
<%= form_with url: philosophers_path, method: :get, class: "search-form m-3",
style: "background-color: #f5f5f5; padding: 5px; width: 100px;" do %>
  <%= text_field_tag :query, params[:query], placeholder: "Type a name",
  class: "search-input shadow sm bg-body-tertiary rounded-4", style: "padding: 10px; border: 1px solid #868686; outline: none; width: 21.5%;" %>
  <%= submit_tag "Search", class: "search-button shadow sm",
  style: "background-color: #333; color: white; padding: 10px 20px; border: none; border-radius: 15px;" %>
<% end %>
<div class="content">

  <% if @philosophers.empty? && params[:query].present? %>
    <p>No such philosophers found. Put a philosopher's name. </p>
  <% elsif @philosophers.empty? %>
    <p>No philosophers available at the moment.</p>
  <% else %>
    <div class="philosophers-cards">
      <% @philosophers.each do |philosopher| %>
        <%= link_to philosopher_path(philosopher), class: 'philosopher-card rounded-4' do %>
          <div class="w-100 rounded-4 philosopher-avatar" style="background-image: url('<%= cl_image_path(philosopher.user.photo.key, height: 250) %>')"></div>
          <div class="philosopher-info">
            <h4><%= philosopher.user.username %></h4>
            <p><strong><%= philosopher.nationality %></strong></p>
            <p class="text-secondary"><%= philosopher.age %> years old</p>
            <p class="text-secondary">Wants to talk about <%= philosopher.preferred_topic %></p>
            <br>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="map-container m-3 rounded-4" style="width: 50%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/philosophers/new.html.erb
<div class="new-philo">
   <div class='d-flex justify-content-center'>
     <div class='signup-card col-6 p-5 m-4 rounded-4 bg-black bg-opacity-50'>

  <h1>Register as a Philosopher</h1>
  <%= simple_form_for @philosopher, url: philosophers_path do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs text-light">
      <%= f.input :age, required: true, input_html: { min: 0 } %>
      <%= f.input :location, required: true %>
      <%= f.input :bio, as: :text, required: true %>
      <%= f.input :price_per_hour, required: true, input_html: { type: 'number', step: 'any' } %>
      <%= f.input :preferred_topic, required: true %>
      <%= f.input :philosophical_focus, required: true %>
      <%= f.input :dress_code, required: true %>
      <%= f.input :nationality, required: true %>
      <%= f.input :communication_style, required: true %>
      <!-- Add other philosopher specific fields as required -->
    </div>

    <div class="form-actions d-flex justify-content-center">
      <%= f.button :submit, "Register as Philosopher", class: "btn btn-dark text-white rounded-4" %>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/philosophers/show.html.erb
<div class="philosopher-name d-flex justify-content-start">
  <button onclick="window.location.href='<%= philosophers_path %>'" class="btn btn-transparent mr-2"><i class="fa-solid fa-chevron-left" style="color: #000000;"></i></button>
<h4><%= @philosopher.user.username %></h4>
</div>
<div class="philosopher-flex">
  <div class="m-3 rounded-4 philosopher-avatar-big" style="background-image: url('<%= cl_image_path(@philosopher.user.photo.key, width: 400) %>')"></div>
  <div class="philosopher-description">
    <p class="bigger-paragraph">🎂 <%= @philosopher.age %> years old</p>
    <p class="bigger-paragraph">🕰️ Available between <%= @philosopher.availability %></p>
    <p class="bigger-paragraph">💰 <%= @philosopher.price_per_hour %>/hour</p>
    <p class="bigger-paragraph">🌎 <%= @philosopher.nationality %></p>
    <p class="bigger-paragraph">❤️ Loves to talk about <%= @philosopher.preferred_topic %></p>
    <p class="bigger-paragraph">🔥 For me it's all about <%= @philosopher.philosophical_focus %></p>
    <p class="bigger-paragraph">👗 <%= @philosopher.dress_code %></p>
    <p class="bigger-paragraph">🗣️ My communication style is <%= @philosopher.communication_style %></p>
    <div class="bg-light p-3 rounded-4">
      <p class="bigger-paragraph text-dark">
        <strong>About me: </strong>
        <em><%= @philosopher.bio %></em>
      </p>
    </div>

<div data-controller="toggle" class="mt-5">
  <!-- Button trigger modal -->
  <button type="button" data-bs-toggle="modal" data-bs-target="#bookDinner" class="btn btn-dark rounded-4 p-3">
    Book a dinner with <%= @philosopher.user.username %>
  </button>

  <!-- Modal -->
  <div class="modal fade" id="bookDinner" tabindex="-1" aria-labelledby="bookDinnerLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-white rounded-4">
        <div class="modal-header">
          <h1 class="modal-title fs-5 text-black" id="bookDinnerLabel">Let's meet!</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= simple_form_for [@philosopher, @dinner] do |f| %>
              <div data-controller="priceupdate">
                <div class="m-5">
                  <%= f.input :date, as: :string, input_html: { data: {controller: "datepicker"} } %>
                  <%= f.input :credit_card %>
                  <%= f.input :length, collection: 1..5, label: 'Dinner duration (hours)', input_html: { id: 'length_input', data: { action: "change->priceupdate#newPrice" } } %><br>
                  <p><strong>Total Price for Dinner:</strong> <span id="total_price" data-priceupdate-target="totalPrice"><%= @philosopher.price_per_hour %></span>€</p>
                  <%= f.button :submit, "Confirm Booking", class: "btn btn-dark rounded-4 p-3" %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>



</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
    var pricePerHour = <%= @philosopher.price_per_hour.to_json %>;
    var lengthInput = document.getElementById("length_input");
    var totalPriceDisplay = document.getElementById("total_price");

    lengthInput.addEventListener("change", function() {
      var length = this.value;
      var totalPrice = pricePerHour * length;
      totalPriceDisplay.textContent = totalPrice;
    });
  });
</script>
</div>

  <div class="map m-3 rounded-4" style="width: 30%;"

    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar text-body">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag "philosofeast.png", class: "logo"  %>
    <% end %>
    <div class="navbar-nav flex-grow-1">
      <div class="d-flex justify-content-end gap-4">
        <% if user_signed_in? %>
          <% if !current_user.philosopher? %>

              <%= link_to "I'm a philosopher", new_philosopher_path, class: "nav-link" %>

          <% end %>

            <%= link_to "Profile", profile_path, class: "nav-link" %>


            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>

        <% else %>

            <%= link_to "Login", new_user_session_path, class: "nav-link" %>

        <% end %>
      </div>
    </div>
  </div>
</div>